spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gundolog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


  data:
    web:
      pageable:
        one-indexed-parameters: true

logging:
  level:
    org.hibernate.sql: debug